### PR TITLE
fix: preserve binding fields

### LINKED ISSUE #61: Binding routes not working
Binding routes not working

```php
Route::multilingual('test/{test:slug}', 'TestController');
```

On reset uri https://github.com/chinleung/laravel-multilingual-routes/blob/v2/src/MultilingualRegistrar.php#L301 the `bindingFields` are cleared.

### PR DESCRIPTION
**Pull request by ricardogobbosouza**
Resolve #61

### CODE REVIEW

**Comment by chinleung** [comment]
@ricardogobbosouza Hey! 👋🏼 

Thanks for the contribution. It seems like the tests are failing after your fix though. Can you fix them please? 😄 

https://github.com/chinleung/laravel-multilingual-routes/runs/4166924873?check_suite_focus=true

**Comment by ricardogobbosouza** [comment]
@chinleung Add a check to see if the methods exists `setBindingFields` and `bindingFields`
They have been added in laravel >= 7.1

**Comment by ricardogobbosouza** [comment]
It might be interesting to release a new version in the future deprecating laravel 5 and 6 =)

**Comment by chinleung** [comment]
> @chinleung Add a check to see if the methods exists `setBindingFields` and `bindingFields` They have been added in laravel >= 7.1

Thanks! 

> It might be interesting to release a new version in the future deprecating laravel 5 and 6 =)

Yeah I'll do that for the next version of Laravel. I think it might break stuff for people if I suddenly remove the support of Laravel 7 and 8 from v2. 😢

**Comment by ricardogobbosouza** [comment]
It would have to be v3 =)

**Pull request merged**
